#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
	herbstclient "$@"
}

hc emit_hook reload

# xsetroot -solid '#5A8E3A'

feh --no-fehbg --bg-scale ~/pictures/wallpapers.jpg

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4 # Use the super key as the main modifier
Alt=Mod1    # Use alt as another modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# volume control
hc keybind $Mod-F10 spawn amixer set Speaker toggle-mute
amixer_mute=amixer set Speaker mute
amixer_unmute=amixer set Speaker unmute
hc keybind Pause spawn amixer-cmus-speaker-off
hc keybind $Mod-F3 spawn amixer set 'PGA1.0 1 Master' 4%-
hc keybind $Mod-F4 spawn amixer set 'PGA1.0 1 Master' 4%+

# brightness control
hc keybind $Mod-F6 spawn xbacklight -dec 5
hc keybind $Mod-F7 spawn xbacklight -inc 5

# program control
hc keybind $Mod-Return spawn xterm tmux
hc keybind $Mod-Shift-i spawn qutebrowser
hc keybind $Mod-Shift-w spawn libreoffice
hc keybind $Mod-Shift-z spawn zathura
hc keybind Print spawn scrot

# touchpad
hc keybind $Mod-Shift-t spawn xinput set-prop 'ALPS0001:01 0911:5288 Touchpad' 'Device Enabled' 0
hc keybind $Mod-t chain , spawn xinput set-prop 'ALPS0001:01 0911:5288 Touchpad' 'Device Enabled' 1 , spawn xinput set-prop 'ALPS0001:01 0911:5288 Touchpad' 'libinput Tapping Enabled' 1 

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# move window to the next workspace
hc keybind $Mod-Shift-comma move_index +1
hc keybind $Mod-Shift-period move_index -1

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u split bottom 0.5
hc keybind $Mod-o split right 0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep

# tags
tag_names=("1" "2")
tag_keys=({1..2} 0)

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}"; do
	hc add "${tag_names[$i]}"
	key="${tag_keys[$i]}"
	if [ -n "$key" ]; then
		hc keybind "$Mod-$key" use_index "$i"
		hc keybind "$Mod-Shift-$key" move_index "$i"
	fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space \
	or , and . compare tags.focus.curframe_wcount = 2 \
	. cycle_layout +1 vertical horizontal max vertical grid \
	, cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace cycle_monitor
hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#333333'
hc set frame_bg_normal_color '#000000'
hc set frame_bg_active_color '#d8d8d8'
hc set frame_border_width 1
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 1
hc set frame_gap 0

# hc attr theme.title_height 15
# hc attr theme.title_when always
# hc attr theme.title_font 'Dejavu Sans:pixelsize=12'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
# hc attr theme.title_depth 3  # space below the title's baseline
# hc attr theme.tab_color '#1F1F1Fdd'
# hc attr theme.active.tab_color '#2B4F0Add'
# hc attr theme.active.tab_outer_color '#6C8257dd'
# hc attr theme.active.tab_title_color '#ababab'
# hc attr theme.normal.title_color '#898989'
# hc attr theme.title_color '#ffffff'
hc attr theme.active.color '#d8d8d8'
hc attr theme.normal.color '#333333'
hc attr theme.urgent.color '#900000'
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#789161'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#606060'
# copy inner color to outer_color
for state in active urgent normal; do
	hc substitute C theme.${state}.inner_color \
		attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

polybar

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1); do
	# start it on each monitor
	"$panel" "$monitor" &
done
